groups:
- name: swarm_task.rules.yml
  rules:
  - alert: ProbeFailed
    expr: probe_success == 0
    for: 3m
    labels:
      severity: error
    annotations:
      summary: "Probe failed {{ $labels.job }} (instance {{ $labels.instance }})"
      description: "Probe failed\n  VALUE = {{ $value }}\n  JOB: {{ $labels.job }}\n LABELS: {{ $labels }}"
  - alert: ExporterDown
    expr: up == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Exporter down {{ $labels.job }} (instance {{ $labels.instance }})"
      description: "Prometheus exporter down\n  VALUE = {{ $value }}\n  JOB: {{ $labels.job }}\n  LABELS: {{ $labels }}"
  - alert: task_high_cpu_usage_200
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m]))
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id)
      * 100 > 200
    for: 5m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' CPU usage is at {{ humanize
        $value}}%.'
      summary: CPU alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name
        }}' on '{{ $labels.container_label_com_docker_swarm_node_id }}'
  - alert: task_high_memory_usage_3g
    expr: sum(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"})
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) > 3e+09
    for: 1m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' memory usage is {{ humanize
        $value}}.'
      summary: Memory alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name
        }}' on '{{ $labels.container_label_com_docker_swarm_node_id }}'
