version: "3.7"

services:

  elasticsearch:
    image: jmb12686/elasticsearch:v7.7.1
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - /mnt/ssd/elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-snapshot:/mnt/elasticsearch-snapshot
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      ES_JAVA_OPTS: "-Xmx1500m -Xms1500m"
      ELASTIC_PASSWORD: changeme
      # discovery.type: single-node
      TZ: America/New_York
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.ssd==true      
      resources:
        limits:
          memory: 2500M
        reservations:
            memory: 2000M

  elastalert:
    image: jmb12686/elastalert:v3.1
    # ports:
    #   - 3030:3030
    #   - 3333:3333
    configs:
      - source: elastalert_config
        target: config/config.json
      - source: elastalert_elastalert
        target: /opt/elastalert/config.yaml
      - source: elastalert_elastalert_test
        target: /opt/elastalert/config-test.yaml
    secrets:
      - elastalert_smtp_auth_file
    volumes:
      - elastalert-rules:/opt/elastalert/rules
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != raspberrypi-beta


  kibana:
    image: jmb12686/kibana:v7.7.1
    # Do not publish ports - force access thru caddy_internal_net
    # ports:
    #   - 5601:5601

    # Legacy - custom runtime commmands to install plugins, spikes CPU and RAM causing infinite crashes...
    # command: /bin/bash -c "/opt/kibana/bin/kibana"
    # command: /bin/bash -c "rm -rf /opt/kibana/optimize/* && /opt/kibana/bin/kibana"
    # command: /bin/bash -c "/opt/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.1.zip && /opt/kibana/bin/kibana"

    environment:
      NODE_OPTIONS: "--max-old-space-size=2048"
      TZ: America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: kibana_config
        target: /opt/kibana/config/kibana.yml
    networks:
      - elk
      - caddy_internal_net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
            memory: 1024M

  filebeat:
    image: jmb12686/filebeat:v7.7.1
    hostname: "{{.Node.Hostname}}"
    user: root
    networks:
      - elk
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    environment:
      - ELASTICSEARCH_HOST:elasticsearch
      - KIBANA_HOST:kibana
    command: ["--strict.perms=false"]
    deploy:
      mode: global

configs:
  elastic_config:
    name: elastic_config-${CONFIG_VERSION:-0}
    file: ./elasticsearch/config/elasticsearch.yml
  kibana_config:
    name: kibana_config-${CONFIG_VERSION:-0}
    file: ./kibana/config/kibana.yml
  filebeat_config:
    name: filebeat_config-${CONFIG_VERSION:-0}
    file: ./filebeat/config/filebeat.yml
  elastalert_config:
    name: elastalert_config-${CONFIG_VERSION:-0}
    file: ./elastalert/config.json
  elastalert_elastalert:
    name: elastalert_elastalert-${CONFIG_VERSION:-0}
    file: ./elastalert/elastalert.yml
  elastalert_elastalert_test:
    name: elastalert_elastalert_test-${CONFIG_VERSION:-0}
    file: ./elastalert/elastalert-test.yml

secrets:
  elastalert_smtp_auth_file:
    file: ./elastalert/smtp_auth_file

networks:
  elk:
    driver: overlay
  caddy_internal_net:
    external: true

volumes:
  filebeat: {}
  elasticsearch-data: {}
  elasticsearch-snapshot:
    driver: glusterfs:latest
    name: "shared-volume/elasticsearch-snapshot"
  elastalert-rules:
    driver: glusterfs:latest
    name: "shared-volume/elastalert-rules"



