global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"
  - "snitch.rules.yml"
  - "healthcheck-io.rules.yml"

alerting:
  alertmanagers:
    - dns_sd_configs:
      - names:
        - 'tasks.alertmanager'
        type: 'A'
        port: 9093  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'doh-status-probe'
    metrics_path: /probe
    params:
      module: [http_2xx_expect_1]  # Look for a HTTP 200 response and expect '1' in body.
    static_configs:
      - targets:
        # - http://prometheus.io    # Target to probe with http.
        - https://bbd96f23-eda8-465d-b190-6ddf056cae66.is-doh.cloudflareresolve.com/resolvertest   # Target to probe with https.
        # - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: doh-status-probe:9115  # The blackbox exporter's real hostname:port.      


